"""updated_ticket_value

Revision ID: 96f8b2ef693d
Revises: 83728d7e7455
Create Date: 2023-12-09 12:51:47.121463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96f8b2ef693d'
down_revision: Union[str, None] = '83728d7e7455'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticket', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('ticket_status_key', 'ticket', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('ticket_status_key', 'ticket', ['status'])
    op.alter_column('ticket', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
